#!/usr/bin/env python3
"""Sestaví data.js — geografii + kandidátky 2026 s lustrací programů."""
from __future__ import annotations

import json
from pathlib import Path

MUNI_CAN = [
    "Místní dopravu, parkování a MHD (organizace, tarify v kompetenci města)",
    "Územní plán, developerské projekty a veřejný prostor",
    "Mateřské a základní školy, které město zřizuje",
    "Obecní byty, sociální služby města a městskou policii",
    "Odpady, zeleň, sportoviště a kulturní příspěvkovky města",
    "Místní poplatky a rozpočet obce/města",
]
MUNI_NO = [
    "Státní daně, důchody, státní sociální dávky",
    "Armádu, zahraniční politiku a azylové řízení státu",
    "Trestní zákony a justici",
    "Celostátní ceny energií a DPH",
    "Vysoké školy a fakultní nemocnice (to je stát/kraj)",
]
MUNI_UP = [
    "Změny zákonů přes poslance, senátory a vládu",
    "Krajské silnice, železnici a velké dopravní stavby",
    "Peníze ze státního rozpočtu a evropské fondy",
    "Pravidla zdravotnictví a školství nastavená státem",
]
SEN_CAN = [
    "Zákony v Senátu (schvalovat, vracet, pozměňovat)",
    "Kontrolu vlády a veřejných institucí",
    "Personálie (soudci ÚS, ombudsman, členové rad ČT/ČRo podle zákona)",
    "Regionální témata zvedat na celostátní úroveň",
]
SEN_NO = [
    "Sami nenařídí MHD, územní plán ani rozpočet městské části",
    "Nestanoví důchody ani daně bez Poslanecké sněmovny a vlády",
    "Neřídí policii v ulicích ani stavební úřad",
]
SEN_UP = [
    "Tlak na vládu a Sněmovnu",
    "Spolupráci s magistrátem a krajem u konkrétních staveb",
    "Evropská témata skrze parlamentní diplomacii",
]


def lus_muni(extra_can=None, extra_no=None, extra_up=None):
    return {
        "canInfluence": MUNI_CAN + (extra_can or []),
        "cannotDecide": MUNI_NO + (extra_no or []),
        "canAdvocate": MUNI_UP + (extra_up or []),
    }


def lus_sen(extra_can=None, extra_no=None, extra_up=None):
    return {
        "canInfluence": SEN_CAN + (extra_can or []),
        "cannotDecide": SEN_NO + (extra_no or []),
        "canAdvocate": SEN_UP + (extra_up or []),
    }


PRAHA_MC = [
    "Praha 1", "Praha 2", "Praha 3", "Praha 4", "Praha 5", "Praha 6", "Praha 7",
    "Praha 8", "Praha 9", "Praha 10", "Praha 11", "Praha 12", "Praha 13",
    "Praha 14", "Praha 15", "Praha 16", "Praha 17", "Praha 18", "Praha 19",
    "Praha 20", "Praha 21", "Praha 22",
    "Praha-Kunratice", "Praha-Libuš", "Praha-Lipence", "Praha-Lochkov",
    "Praha-Lysolaje", "Praha-Nebušice", "Praha-Nedvězí", "Praha-Petrovice",
    "Praha-Přední Kopanina", "Praha-Řeporyje", "Praha-Satalice", "Praha-Slivenec",
    "Praha-Suchdol", "Praha-Šeberov", "Praha-Štěrboholy", "Praha-Troja",
    "Praha-Újezd", "Praha-Velká Chuchle", "Praha-Vinoř", "Praha-Zbraslav",
    "Praha-Zličín", "Praha-Běchovice", "Praha-Benice", "Praha-Březiněves",
    "Praha-Čakovice", "Praha-Ďáblice", "Praha-Dolní Chabry",
    "Praha-Dolní Měcholupy", "Praha-Dolní Počernice", "Praha-Dubeč",
    "Praha-Klánovice", "Praha-Koloděje", "Praha-Kolovraty", "Praha-Královice",
    "Praha-Křeslice",
]
BRNO_MC = [
    "Brno-střed", "Brno-sever", "Brno-jih", "Brno-Královo Pole", "Brno-Bystrc",
    "Brno-Žabovřesky", "Brno-Židenice", "Brno-Líšeň", "Brno-Vinohrady",
    "Brno-Kohoutovice", "Brno-Komín", "Brno-Nový Lískovec", "Brno-Starý Lískovec",
    "Brno-Bohunice", "Brno-Bosonohy", "Brno-Chrlice", "Brno-Ivanovice",
    "Brno-Jehnice", "Brno-Jundrov", "Brno-Kníničky",
    "Brno-Maloměřice a Obřany", "Brno-Medlánky", "Brno-Ořešín",
    "Brno-Řečkovice a Mokrá Hora", "Brno-Slatina", "Brno-Tuřany",
    "Brno-Útěchov", "Brno-Žebětín", "Brno-Černovice",
]
PARDUBICE_MO = [
    ("Pardubice I", "Zelené a Bílé Předměstí"),
    ("Pardubice II", "Polabiny"),
    ("Pardubice III", "Studánka, Cihelna"),
    ("Pardubice IV", "Pardubičky, Černá za Bory a okolí"),
    ("Pardubice V", "Nové Jesenčany a okolí"),
    ("Pardubice VI", "Svítkov, Popkovice"),
    ("Pardubice VII", "Ohrazenice"),
    ("Pardubice VIII", "Hostovice a okolí"),
]


def bodies():
    out = [
        {"id": "praha", "city": "Praha", "kind": "city", "name": "Zastupitelstvo hl. m. Prahy", "seats": 65},
        {"id": "brno", "city": "Brno", "kind": "city", "name": "Zastupitelstvo města Brna", "seats": 55},
        {"id": "pardubice", "city": "Pardubice", "kind": "city", "name": "Zastupitelstvo města Pardubic", "seats": 39},
        {"id": "sen-21", "city": "Praha", "kind": "senate", "name": "Senát č. 21 — Praha 5", "seats": 1},
        {"id": "sen-24", "city": "Praha", "kind": "senate", "name": "Senát č. 24 — Praha 9", "seats": 1},
        {"id": "sen-27", "city": "Praha", "kind": "senate", "name": "Senát č. 27 — Praha 1", "seats": 1},
        {"id": "sen-60", "city": "Brno", "kind": "senate", "name": "Senát č. 60 — Brno-město", "seats": 1},
    ]
    for name in PRAHA_MC:
        slug = name.lower().replace(" ", "-").replace("á", "a")
        out.append({"id": f"praha-mc-{name}", "city": "Praha", "kind": "district", "name": name, "seats": None})
    for name in BRNO_MC:
        out.append({"id": f"brno-mc-{name}", "city": "Brno", "kind": "district", "name": name, "seats": None})
    for name, note in PARDUBICE_MO:
        out.append({"id": f"pce-mo-{name}", "city": "Pardubice", "kind": "district", "name": name, "note": note, "seats": None})
    return out


def L(**kwargs):
    kwargs.setdefault("promises", [])
    kwargs.setdefault("topics", [])
    kwargs.setdefault("controversies", [])
    kwargs.setdefault("sources", [])
    kwargs.setdefault("trackRecord", {"positive": [], "negative": []})
    if "lustration" not in kwargs:
        kwargs["lustration"] = lus_muni()
    return kwargs


def praha():
    b = "praha"
    return [
        L(id="praha-spolu", bodyId=b, party="SPOLU pro Prahu (ODS a TOP 09)", short="SPOLU",
          leader="Tomáš Portlík", leaderRole="starosta Prahy 9, kandidát na primátora",
          results2022={"percent": 24.72, "mandates": 19, "predecessor": "SPOLU ODS+TOP 09+KDU-ČSL",
                       "detail": "Vítěz 2022. Lidovci letos odešli k Praze sobě. Primátor Svoboda už nekandiduje."},
          topics=["Tým starostů městských částí", "Doprava a výstavba", "Kontinuita koalice 2023–2026"],
          promises=["Dokončit rozjeté dopravní stavby", "Stabilní vedení města bez experimentů", "Důraz na bezpečnost a údržbu"],
          summary="Klasická pravicová koalice, tentokrát jen ODS a TOP 09. Vedou ji starostové, ne Svoboda. Slibují spíš dotahovat to, co už běží, než otáčet město naruby.",
          trackRecord={"positive": ["Po 2022 vyhráli volby a sestavili koalici se STAN a Piráty.", "Město udrželo rating a velké investiční akce (metro, okruh v přípravě)."],
                       "negative": ["Koalice se skládala měsíce, image chaosu.", "KDU-ČSL ze značky SPOLU v Praze odešli — značka je užší než v roce 2022."]},
          controversies=["Dlouhé sestavování rady 2022/23", "Spor o podobu rozvoje a o to, kdo „vládne“ mezi magistrátem a městskými částmi"],
          lustration=lus_muni(["Složení rady a primátora", "Velké dopravní stavby v gesci Prahy"]),
          sources=["ČSÚ 2022", "iDNES 6/2026 — Portlík a kandidátka", "Wikipedie ZHMP 2026"]),
        L(id="praha-ano", bodyId=b, party="ANO 2011", short="ANO",
          leader="Jan Hušbauer", leaderRole="zastupitel Prahy 4, kandidát na primátora",
          results2022={"percent": 19.34, "mandates": 14, "detail": "Druzí v roce 2022, v opozici. Původní lídr 2026 Ondřej Prokop odstoupil kvůli bytům."},
          topics=["Doprava bez restrikcí", "Dostupnější bydlení v rétorice hnutí", "Kritika stávající koalice"],
          promises=["Méně zákazů v centru", "Tlak na rychlejší výstavbu", "Úspory a „zdravý selský rozum“"],
          summary="Hnutí, které v Praze bývá silné v okrajových částech. Letos mění lídra za pochodu: Prokop po kauze bytů skončil, místo něj Hušbauer. Chtějí porazit současnou koalici.",
          trackRecord={"positive": ["Stabilně druhá síla magistrátu 2022.", "Silné zastoupení v některých MČ."],
                       "negative": ["V Praze 2022–26 v opozici, málo konkrétních magistrátních stop.", "Výměna lídra těsně před volbami."]},
          controversies=["Ondřej Prokop a nevyjasněné byty (6/2026), konec v politice", "Celostátní spory ANO o brněnské zastupitele 2025 (jinde, ale medially silné)"],
          sources=["ČSÚ 2022", "Seznam Zprávy 6/2026 a 8/2026"]),
        L(id="praha-pirati", bodyId=b, party="Česká pirátská strana", short="Piráti",
          leader="Tereza Nislerová", leaderRole="ekonomka, zastupitelka Prahy 4",
          results2022={"percent": 17.73, "mandates": 13, "detail": "Třetí místo. V koalici se SPOLU a STAN od 2023. Hřib odešel do Sněmovny."},
          topics=["Transparentnost", "Městská data a služby", "Doprava a klima v pirátském balení"],
          promises=["Pokračovat v digitalizaci", "Hlídání veřejných zakázek", "Město přívětivé k MHD a cyklistice"],
          summary="Po Hřibovi vedou magistrátní kampaň s novou tváří. Pořád jsou součástí vládnoucí koalice, ale část lidí (Komrsková) odešla k JSME PRAHA. Voliči uvidí, jestli značka Piráti v Praze ještě táhne.",
          trackRecord={"positive": ["Dlouhodobě silní v Praze, digitalizace a otevřená data.", "Podíl na koalici 2023–26."],
                       "negative": ["Odchody známých tváří.", "Mediální tření kvůli lídryni a práci v Orlen Unipetrol."]},
          controversies=["CNN Prima: Nislerová a Orlen — střet image vs. ropná firma", "Odchod náměstkyně Komrskové k jiné kandidátce"],
          sources=["ČSÚ 2022", "Wikipedie ZHMP 2026"]),
        L(id="praha-sobě", bodyId=b, party="PRAHA SOBĚ, KDU-ČSL a Strana zelených", short="Praha sobě+",
          leader="Adam Scheinherr", leaderRole="předseda Prahy sobě, exnáměstek pro dopravu",
          results2022={"percent": 14.73, "mandates": 11, "predecessor": "Praha sobě samostatně",
                       "detail": "Čtvrtí. V opozici po rozpadu aliance s Piráty. Letos spojenectví s lidovci a zelenými. Čižinský je na 3. místě."},
          topics=["Doprava (tramvaje, lávky, zklidnění)", "Bydlení", "Přímá volba primátora", "Zeleň a klima"],
          promises=["Pro Prahu první poslední", "Pokračovat v dopravních stavbách, které Scheinherr táhl", "Víc pravomocí lidem — debata o přímé volbě primátora"],
          summary="Místní značka Jana Čižinského teď vede Scheinherr a rozšířila se o lidovce a zelené. Je to spíš „městská levý střed + katolíci + eko“ než čistá Praha sobě z roku 2018/22.",
          trackRecord={"positive": ["Scheinherr jako náměstek dopravy: viditelné stavby a komunikace k MHD.", "Praha sobě má silné kořeny v Praze 7 a komunitní politice."],
                       "negative": ["Po 2022 nedohodli vládnutí s Piráty, skončili v opozici.", "Značka se ředí koalicí tří subjektů."]},
          controversies=["Rozpad „aliance stability“ s Piráty 2023", "Debata, zda přímá volba primátora patří do komunálu (ústava)"],
          lustration=lus_muni(["Konkrétní dopravní stavby v gesci Prahy"], extra_up=["Změna ústavy kvůli přímé volbě primátora — to Praha sama neudělá"]),
          sources=["ČSÚ 2022", "iDNES 6/2026", "Seznam Zprávy k přímé volbě"]),
        L(id="praha-stan", bodyId=b, party="STAROSTOVÉ A NEZÁVISLÍ", short="STAN",
          leader="Petr Hlaváček", leaderRole="náměstek primátora pro územní rozvoj, architekt",
          results2022={"percent": 7.77, "mandates": 5, "detail": "V koalici od 2023. Stejný lídr jako minule."},
          topics=["Územní plán", "Architektura a rozvoj", "Městské části"],
          promises=["Klidnější a předvídatelnější výstavba", "Kvalita veřejného prostoru", "Spolupráce s MČ"],
          summary="Malý, ale vládnoucí klub. Hlaváček je tvář územního rozvoje — kdo chce vědět, kam Praha poroste, má ho na radaru. Kdo čeká protestní opozici, tohle není.",
          trackRecord={"positive": ["Gesce územního rozvoje v radě.", "Kontinuita lídra."],
                       "negative": ["Jen 5 mandátů — malý vliv bez partnerů.", "Rozvojové spory (výškové stavby, brownfieldy) se lepí na něj."]},
          controversies=["Spory o územní plán a velké developmenty"],
          sources=["ČSÚ 2022", "Seznam Zprávy 3/2026"]),
        L(id="praha-spd", bodyId=b, party="SPD pro Prahu s podporou Trikolory, PRO, Přísahy a NK", short="SPD+",
          leader="Milan Urban", leaderRole="architekt, předseda klubu SPD v ZHMP",
          results2022={"percent": 5.17, "mandates": 3, "predecessor": "SPD + Trikolora + PES",
                       "detail": "Těsně přes práh. Letos širší spojenectví s PRO a Přísahou."},
          topics=["Migrace a bezpečnost (celostátní agenda v komunálu)", "Kritika Green Deal ve městě", "Nízké výdaje"],
          promises=["Méně „ideologie“ v MHD a školách", "Důraz na bezpečnost", "Skeptický postoj k klimatickým restrikcím"],
          summary="Protistystémový blok na magistrátu. Hodně mluví o věcech, které Praha sama nenařídí (imigrace, EU). V zastupitelstvu jsou od 2022 tři.",
          trackRecord={"positive": ["Udrželi se v zastupitelstvu 2022."],
                       "negative": ["Minimální vliv na radu.", "Program často sklouzává k celostátním tématům."]},
          controversies=["Celostátní kauzy SPD a Okamury se přenášejí i na městskou značku"],
          lustration=lus_muni(extra_no=["Azylovou a migrační politiku státu SPD v Praze nezmění"]),
          sources=["ČSÚ 2022", "Seznam Zprávy 2/2026"]),
        L(id="praha-jsme", bodyId=b, party="JSME PRAHA", short="JSME PRAHA",
          leader="Jana Komrsková", leaderRole="náměstkyně primátora, dříve Piráti",
          results2022={"note": "Nové uskupení (TEAM / Volt a odchozí z Pirátů). V roce 2022 jako celek nekandidovali."},
          topics=["Odchod od Pirátů", "Vedení města zevnitř", "Volt a „jsme team“"],
          promises=["Jiná kultura koalice než u mateřských Pirátů", "Pragmatické řízení"],
          summary="Nová značka kolem náměstkyně, která odešla od Pirátů. Část voličů to čte jako rozkol, část jako osobní projekt. Stopa 2022 nemají — jsou ve hře kvůli aktuální radě.",
          trackRecord={"positive": ["Komrsková už teď sedí v radě a zná úřad."],
                       "negative": ["Nulový výsledek pod touto značkou.", "Odchody z Pirátů tříští progresivní voliče."]},
          controversies=["Odchod z Pirátů po kauze/konopí Veverky a dalších třeních (2026)"],
          sources=["Wikipedie ZHMP 2026", "Novinky 6/2026"]),
        L(id="praha-auto", bodyId=b, party="Motoristé sobě", short="AUTO",
          leader="Klára Sovová", leaderRole="podnikatelka, Luční a Labská bouda",
          results2022={"note": "V ZHMP 2022 nekandidovali / bez mandátu. Celostátně posílili až 2025."},
          topics=["Auta a zklidňování restrikcí", "Parkování", "Odpor k „válce proti autům“"],
          promises=["Víc respektu k řidičům", "Méně zón a zákazů", "Pragmatická doprava"],
          summary="Nová celostátní značka v Praze. Lídryně je z Krkonoš, ne z magistrátní kuchyňky — to je buď svěží vzduch, nebo slabá znalost města. Program se točí kolem aut.",
          trackRecord={"positive": ["Silná celostátní vlna Motoristů po sněmovních volbách 2025."],
                       "negative": ["Žádná magistrátní stopa 2022–26.", "Lídryně mimo pražskou komunální praktiku."]},
          controversies=["Sovová dříve ODS; otázky, co je lokální a co marketing značky"],
          lustration=lus_muni(["Parkovací politika a organizace dopravy v Praze"], extra_no=["Dálniční síť a spotřební daň z paliv"]),
          sources=["Seznam Zprávy 6/2026", "iDNES"]),
        L(id="praha-sen", bodyId=b, party="SEN PRO PRAHU s Václavem Láskou (SEN 21, HPP 11, Mourek)", short="SEN pro Prahu",
          leader="Václav Láska", leaderRole="senátor, obvod Praha 5",
          results2022={"note": "Nová magistrátní kandidátka. Láska obhajuje senát v obvodu 21."},
          topics=["Senátní zkušenost", "Městské části (HPP 11)", "Liberální střed"],
          promises=["Most mezi Senátem a magistrátem", "Transparentnost", "Podpora lokálních značek"],
          summary="Senátor skládá vlastní městskou listinu. Výhoda: jméno. Nevýhoda: SEN 21 nikdy Praha jako celek neřídila. Zároveň kandiduje do Senátu — dvojí kampaň.",
          trackRecord={"positive": ["Láska je známý senátor, SEN 21 má stopu v horní komoře."],
                       "negative": ["Na magistrátu bez klubu 2022."]},
          controversies=["Souběh senátní obhajoby a magistrátní jedničky"],
          sources=["neovlivni.cz", "Wikipedie ZHMP 2026"]),
        L(id="praha-levice", bodyId=b, party="Levice", short="Levice",
          leader="Pavel Čižinský", leaderRole="advokát (současně senát Praha 1)",
          results2022={"note": "Na ZHMP 2022 jako Levice bez mandátu / mimo hlavní šestku."},
          topics=["Dostupné bydlení", "Sociální politika města", "Kritika developmentu"],
          promises=["Víc městských bytů", "Regulace Airbnb v kompetenci města", "Služby, ne spekulace"],
          summary="Levicová alternativa k Praze sobě. Pavel Čižinský je jiné křídlo rodiny než Jan na Praze sobě. Současně běží do Senátu na Praze 1.",
          trackRecord={"positive": ["Dlouhodobá advokační práce k bydlení a cizineckému právu."],
                       "negative": ["Na magistrátu bez reálné většiny."]},
          controversies=["Souběh senátní a komunální kandidatury", "Štípení „čizínkovského“ elektorátu"],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-sleva", bodyId=b, party="Spojená levice pro Prahu (KSČM, ČSSD, KSČ)", short="Spojená levice",
          leader="Petr Vlček",
          results2022={"note": "KSČM ani ČSSD v ZHMP 2022 samostatně nepřekročily práh do rady; bez mandátu v hlavní šestce."},
          topics=["Sociální jistota", "Městské služby", "Kritika privatizace"],
          promises=["Levnější MHD v slibech", "Obecní bydlení", "Odpor k „pravicové“ koalici"],
          summary="Stará levice pod jednou střechou. V Praze 2022 se do ZHMP nedostali — letos zkoušejí součet značek. Elektorát je starší, program klasicky sociální.",
          trackRecord={"positive": ["Historická stopa KSČM v některých MČ."],
                       "negative": ["Dlouhodobý úpadek na magistrátní úrovni."]},
          controversies=["Nostalgie po KSČ / značka KSČ v názvu koalice je pro část voličů stopka"],
          sources=["ČTK / Pražský deník 8/2026"]),
        L(id="praha-patrioti", bodyId=b, party="PATRIOTI PRO PRAHU", short="Patrioti",
          leader="Jiří Vítek",
          results2022={"note": "Mimo zastupitelstvo 2022."},
          topics=["Národní agenda v Praze", "Bezpečnost", "Kritika migrace a EU"],
          promises=["Praha „česká“ v kultuře a symbolice", "Tvrdší postoj k nelegálnímu jednání ve veřejném prostoru"],
          summary="Národně laděná listina mimo SPD. Na magistrátu zatím bez mandátu. Hodně celostátních hesel, málo pák v Kompetenčním zákoně obce.",
          trackRecord={"positive": [], "negative": ["Bez mandátu 2022, neznámá výkonnost v radě."]},
          controversies=["Překryv s SPD a dalšími protestními značkami — tříštění hlasů"],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-gen", bodyId=b, party="GEN s podporou veřejnosti", short="GEN",
          leader="Roman Mejstřík",
          results2022={"note": "Bez mandátu v ZHMP 2022."},
          topics=["Generační politika", "Kritika stávajících stran"],
          promises=["Obměna personálií", "Jiné priority než velká šestka"],
          summary="Menší strana s plnou 65člennou listinou. Pro voliče nespokojené s velkými značkami, ale bez dokázané magistrátní síly.",
          trackRecord={"positive": [], "negative": ["Bez vlivu 2022–26."]},
          controversies=[],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-nasse", bodyId=b, party="Naše Praha SNK ED", short="SNK ED",
          leader="Jiří Benýšek",
          results2022={"note": "Bez mandátu v ZHMP 2022."},
          topics=["Evropští demokraté", "Lokální Praha"],
          promises=["Konzervativně-liberální správa", "Méně ideologie"],
          summary="Zbytek značky SNK Evropští demokraté. V Praze 2022 mimo hru o radu. 41 kandidátů, ne plná 65.",
          trackRecord={"positive": ["Historie SNK ED v 00. letech."], "negative": ["Dlouho mimo magistrát."]},
          controversies=[],
          sources=["Wikipedie ZHMP 2026", "iDNES 9/2026"]),
        L(id="praha-svobodni", bodyId=b, party="Svobodní", short="Svobodní",
          leader="Bedřich Laube", leaderRole="zároveň senát Praha 9 za širší pravicovou koalici",
          results2022={"note": "Bez mandátu ZHMP 2022."},
          topics=["Nízké daně a poplatky města", "Méně regulace", "Auta a podnikání"],
          promises=["Škrtat výdaje", "Bránit restrikcím v dopravě", "Svoboda podnikání"],
          summary="Libertariánská klasika. Laube je i na senátní kandidátce. Magistrát umí ovlivnit poplatky a regulace, ne státní daně — to v lustraci padá do „nerozhodují“.",
          trackRecord={"positive": [], "negative": ["Bez mandátu na magistrátu."]},
          controversies=[],
          lustration=lus_muni(extra_no=["Sazby DPH a daně z příjmu Svobodní v Praze nezmění"]),
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-rezidenti", bodyId=b, party="REZIDENTI – REBELOVÉ pro změnu Prahy", short="Rebelové",
          leader="Martin Motl",
          results2022={"note": "Nové / okrajové sdružení (Rebelové, NSS, NK)."},
          topics=["Změna Prahy", "Rezidentská agenda"],
          promises=["Hlas „běžných Pražanů“ proti etablovaným stranám"],
          summary="Protestní sdružení s plnou listinou. Bez stopy v radě. Program je spíš značka vzdoru než správa města.",
          trackRecord={"positive": [], "negative": ["Bez mandátu, nejasná vyjednávací síla."]},
          controversies=["Složení s NSS a Rebelů — ověřit konkrétní personálie"],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-dsz", bodyId=b, party="DSZ – Za práva zvířat a NK", short="DSZ",
          leader="Hana Janišová",
          results2022={"note": "Okrajová listina, 9 kandidátů."},
          topics=["Práva zvířat", "Útulky", "Městské vyhlášky k chovu"],
          promises=["Lepší útulky a vyhlášky", "Téma zvířat ve městě"],
          summary="Jednoúčelová listina. Město opravdu zřizuje útulky a může vyhláškou něco ovlivnit. Velkou politiku Prahy neotočí.",
          trackRecord={"positive": ["Jasné téma."], "negative": ["Úzký záběr, málo kandidátů."]},
          controversies=[],
          lustration=lus_muni(["Městské útulky, vyhlášky k volnému pobíhání, veřejná zeleň"]),
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-voluntia", bodyId=b, party="Libertariánská strana Voluntia", short="Voluntia",
          leader="Tadeáš Janků",
          results2022={"note": "15 kandidátů, bez mandátu 2022."},
          topics=["Minimalismus státu/města", "Dobrovolnost"],
          promises=["Méně nařizování", "Odmítání politických funkcí v duchu libertariánství (částečně)"],
          summary="Ještě tvrdší libertariánství než Svobodní. 15 jmen. Spíš signál než správa 65členného zastupitelstva.",
          trackRecord={"positive": [], "negative": ["Bez vlivu."]},
          controversies=[],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-lepsi-zivot", bodyId=b, party="LEPŠÍ ŽIVOT PRO LIDI", short="Lepší život",
          leader="Pavel Opl",
          results2022={"note": "10 kandidátů. Program v názvu: daně, mzdy, důchody, energie — vesměs státní agenda."},
          topics=["Mzdy a důchody", "Ceny energií", "Daň z nemovitostí"],
          promises=["Min. mzda 50 tis., důchod 30 tis., ceny energií 2019 — jak je v názvu listiny"],
          summary="Název slibuje věci, které zastupitelstvo Prahy neschvaluje. Daň z nemovitostí částečně ano (koeficienty), mzdy a důchody ne. Typický případ na lustraci.",
          trackRecord={"positive": [], "negative": ["Bez mandátu, program mimo kompetenci."]},
          controversies=[],
          lustration=lus_muni(
              extra_can=["Koeficient daně z nemovitých věcí v Praze"],
              extra_no=["Minimální mzda, státní důchody, cenová regulace energií celostátně", "Válka a mír"],
          ),
          sources=["Wikipedie ZHMP 2026 — plný název listiny"]),
        L(id="praha-mimozemstane", bodyId=b, party="ANO LEPŠÍ ČESKO S MIMOZEMŠŤANY", short="Mimozemšťané",
          leader="Jiří Dubský",
          results2022={"note": "Recesistická / protestní listina, 3 kandidáti. Neplést s ANO 2011."},
          topics=["Protest / recese"],
          promises=["Není relevatní program města v běžném smyslu"],
          summary="Tři jména, recese v názvu. Nejsou to Babišovo ANO. Pro databázi proto, aby se to nepletlo na lístku.",
          trackRecord={"positive": [], "negative": ["Bez správní relevance."]},
          controversies=["Zmatení značky ANO"],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-asocialove", bodyId=b, party="Česká strana asociálů", short="ČSA",
          leader="Lia Nova",
          results2022={"note": "Recese, 3 kandidáti."},
          topics=["Satira"],
          promises=[],
          summary="Satirická minilistina. Do rady města se nehraje.",
          trackRecord={"positive": [], "negative": []},
          controversies=[],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-urza", bodyId=b, party="Urza.cz", short="Urza",
          leader="Martin Urza",
          results2022={"note": "1 kandidát. Program: nechtějí funkce."},
          topics=["Anarchokapitalismus", "Odmítnutí politické moci"],
          promises=["Odmítnou každou politickou funkci — dle názvu listiny"],
          summary="Kandidují s tím, že vládnout nechtějí. To je férově řečeno v názvu. Pro lustraci: kdyby náhodou, pořád by magistrát funkce měl — oni je prý vezmou.",
          trackRecord={"positive": ["Otevřenost ohledně cíle."], "negative": ["Nekompatibilní se správou města."]},
          controversies=[],
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-litacka", bodyId=b, party="VELKÝ KŘÍŽEK PRO LÍTAČKU ZA KAČKU – SOUSEDÉ PRO PRAHU", short="Lítačka za kačku",
          leader="Hugo Štolba",
          results2022={"note": "4 kandidáti. Jedno téma: jízdné."},
          topics=["Jízdné MHD", "Lítačka"],
          promises=["Symbolicky: lítačka za korunu"],
          summary="Jedno téma, které Praha teoreticky ovlivní (tarify PID v rámci dohod). Se čtyřmi jmény ale koalici nesloží.",
          trackRecord={"positive": ["Téma v kompetenci města/PID."], "negative": ["Minilistina."]},
          controversies=[],
          lustration=lus_muni(["Tarify MHD v Praze (spolu s PID a Středočeským krajem)"]),
          sources=["Wikipedie ZHMP 2026"]),
        L(id="praha-cibulka", bodyId=b, party="Volte Pravý Blok (Petr Cibulka)", short="Pravý Blok",
          leader="Petr Cibulka",
          results2022={"note": "14 kandidátů. Trvalá protestní značka."},
          topics=["Přímá demokracie", "Odvolatelnost politiků", "Protikorupční narrativa"],
          promises=["Referenda", "Odvolatelnost"],
          summary="Dlouholetá cibulkovská listina s programem v názvu. Komunál referenda částečně umí (místní), odvolatelnost poslanců ne.",
          trackRecord={"positive": [], "negative": ["Bez mandátu, program mix obce a ústavy."]},
          controversies=["Konspirační a ostrá rétorika značky"],
          lustration=lus_muni(["Místní referendum"], extra_no=["Odvolatelnost poslanců a státních úředníků přímo občany — ústava"]),
          sources=["Wikipedie ZHMP 2026"]),
    ]


def brno():
    b = "brno"
    return [
        L(id="brno-ano", bodyId=b, party="ANO 2011", short="ANO",
          leader="Václav Trojan", leaderRole="poslanec, místostarosta Brno-Židenice, pěstírna konopí v povolání na listině",
          results2022={"mandates": 13, "detail": "13 zastupitelů. Vedení hnutí 2025 nařídilo odchod z koalice; většina neuposlechla a byla vyloučena. Ti teď kandidují jako Brnoklidem."},
          topics=["Nová tvář po rozkolu", "Kritika ODS/Vaňkové éry", "Zdravotnictví (Ludka na 2. místě)"],
          promises=["Jiné Brno než koalice 2022–26", "Pořádek a investice v rétorice ANO"],
          summary="Oficiální ANO v Brně je po čistce jiné než klub, který seděl v koalici. Lídr Trojan je poslanec a židenický místostarosta. Část voličů může plést ANO a Brnoklidem.",
          trackRecord={"positive": ["V roce 2022 silný výsledek (13 mandátů)."],
                       "negative": ["Rozkol 2025: značka vs. lidé, co reálně vládli.", "Mediální obraz pěstírny konopí u lídra."]},
          controversies=["Vyloučení brněnských zastupitelů ANO (2025)", "Trojan a konopná pěstírna (Novinky 6/2026)"],
          sources=["Wikipedie ZMB 2026", "Seznam Zprávy", "Novinky"]),
        L(id="brno-ods", bodyId=b, party="ODS, TOP 09 a nezávislí", short="SPOLEČNĚ",
          leader="Kamila Zlatušková", leaderRole="televizní producentka, nestranička; Vaňková nekandiduje ze zdraví",
          results2022={"predecessor": "SPOLEČNĚ ODS+TOP 09", "detail": "Jádro koalice 2022–26. Primátorka Vaňková končí."},
          topics=["Kontinuita správy", "Nová tvář místo Vaňkové", "Starostové MČ na listině"],
          promises=["Dotáhnout projekty", "Stabilita po éře Vaňkové", "Kultura a značka města (Zlatušková z televize)"],
          summary="Vládnoucí pravice s novou lídryní mimo stranický aparát. Buď to omladí značku, nebo to voliči přečtou jako marketing. Na listině jsou Aberl, Pazderová, Mencl — úřad znají.",
          trackRecord={"positive": ["Vedli město většinu období.", "Síť starostů MČ."],
                       "negative": ["Únava z dlouhého vládnutí.", "Odchod ANO z koalice (fakticky rozpolcené).", "Zdravotní konec Vaňkové mění kampaň."]},
          controversies=["Piráti si rýpli do nominace Zlatuškové", "Rozpad původně široké koalice"],
          sources=["Wikipedie ZMB 2026", "TOP 09 5/2026"]),
        L(id="brno-kdu", bodyId=b, party="Lidovci a Starostové – Brno blíž lidem (KDU-ČSL a STAN)", short="KDU+STAN",
          leader="Jakub Hruška", leaderRole="starosta Brno-Kohoutovice",
          results2022={"detail": "Koalice KDU+STAN byla ve vedení města. Hladík (exministr) je na listině, jedničkou je Hruška."},
          topics=["Školství (Matonohová)", "MČ a starostové", "Klidnější vedení"],
          promises=["Přívětivější úřad", "Školy a služby", "Pokračování spolupráce lidovců a STAN"],
          summary="Druhý pilíř končící koalice. Místo velkých ideologií starostenské řemeslo. Hladík je zátěž i bonus podle toho, kdo si pamatuje ministerstvo životního prostředí.",
          trackRecord={"positive": ["Účast v radě, gesce školství.", "Síť MČ (Kohoutovice, Medlánky, Tuřany)."],
                       "negative": ["Hladík — celostátní kauzy a mediální obraz z ministerstva."]},
          controversies=["Petr Hladík a kauzy MŽP v celostátních médiích"],
          sources=["Novinky 11/2025", "Metro 4/2026"]),
        L(id="brno-tu", bodyId=b, party="Piráti a Fakt Brno TU! (Piráti, Fakt Brno, Idealisté, GEN)", short="TU!",
          leader="Adam Zemek", leaderRole="zastupitel, programátor",
          results2022={"predecessor": "Piráti", "detail": "Piráti měli jít do koalice 2022, na poslední chvíli nešli. Teď širší TU!"},
          topics=["Opozice k ODS", "Město krátkých vzdáleností", "Transparentnost"],
          promises=["Cíl kolem 20 % (kampaň)", "Jiné priority než Zlatušková/ODS", "Fakt Brno a architektura (Bidlová)"],
          summary="Piráti plus místní Fakt Brno. Po odmítnutí koalice 2022 jsou čtyři roky mimo radu — buď trest, nebo čistota. Zemek je méně známý než kdysi Hřib v Praze.",
          trackRecord={"positive": ["Opoziční dohled 2022–26.", "Spojení s Fakt Brno (městská značka)."],
                       "negative": ["Nešli do koalice, vliv na výkon byl menší."]},
          controversies=["Vztah k ODS a nominaci Zlatuškové (Deník N 4/2026)"],
          sources=["Wikipedie ZMB 2026", "Deník N"]),
        L(id="brno-zeleni", bodyId=b, party="ZELENÉ BRNO (Zelení, Žít Brno, SEN 21, LES, Volt, Budoucnost, Kruh)", short="Zelené Brno",
          leader="Natálie Vencovská", leaderRole="designérka, veřejný prostor; s Drápalovou a Fuchsovou v čele",
          results2022={"predecessor": "Zelení (+ Žít Brno historicky)", "detail": "Letos široká eko-liberální střecha."},
          topics=["Veřejný prostor", "Klima", "Žít Brno tradice", "Komunitní politika"],
          promises=["Město pro lidi, ne jen auta", "Kvalita ulic", "Spolupráce malých značek"],
          summary="Široká zelená duha. Drápalová (Nový Lískovec) dodává starostenskou důvěryhodnost, Vencovská novost. Riziko: moc log na jedné listině.",
          trackRecord={"positive": ["Jana Drápalová — dlouhá starostenská stopa.", "Žít Brno kdysi změnilo brněnskou politiku."],
                       "negative": ["Roztříštěnost malých partnerů."]},
          controversies=[],
          sources=["Zelení Brno 3/2026", "Novinky 6/2026"]),
        L(id="brno-klidem", bodyId=b, party="Brnoklidem", short="Brnoklidem",
          leader="Karin Podivinská", leaderRole="náměstkyně primátorky, dříve ANO; s ní Šimek a Landa",
          results2022={"note": "Značka nová. Jádro = vyloučení zastupitelé ANO, kteří zůstali v koalici. Výsledek 2022 se počítá pod ANO."},
          topics=["Klid, ne stranický bič z Prahy", "Kontinuita rady", "Místní ANO bez Babiše"],
          promises=["Vládnout dál bez příkazů z hnutí", "Zkušenost z úřadu"],
          summary="Nejsledovanější brněnský rozkol. Lidé, co město fakt táhli za ANO, teď kandidují proti oficiálnímu ANO. Volič ANO musí vybrat značku, nebo tváře.",
          trackRecord={"positive": ["Reálná výkonná stopa v radě 2022–26.", "Šimek (exhejtman) jako známé jméno."],
                       "negative": ["Rozbitý vztah s mateřským hnutím.", "Otázka loajality a slibů z roku 2022."]},
          controversies=["Vyloučení z ANO 2025", "Seznam Zprávy 8/2026: kampaň i „u záchodů“ / psi na kandidátce jako recese"],
          sources=["Novinky 4/2026", "Seznam Zprávy 8/2026"]),
        L(id="brno-luzanky", bodyId=b, party="Za Lužánky", short="Za Lužánky",
          leader="Jana Tichá Janulíková", leaderRole="ředitelka TIC Brno",
          results2022={"note": "Nové hnutí kolem stadionu Za Lužánkami a fanoušků Zbrojovky."},
          topics=["Stadion Za Lužánkami", "Sport", "Fanouškovská politika"],
          promises=["Protlačit stadion politicky", "Téma sportovišť"],
          summary="Jedno velké téma, které město opravdu řeší (pozemky, peníze, územní plán). Riziko: hnutí ze stadionu a stín Slušných lidí u jednoho ze zakladatelů.",
          trackRecord={"positive": ["Jasné, místní téma.", "Janulíková zná městskou prezentaci (TIC)."],
                       "negative": ["Úzký program.", "Richard Novák a minulost u Slušných lidí — medializace."]},
          controversies=["Kontakt se zrušeným hnutím Slušní lidé u zakladatele", "Byznys stadionu (Metrostav aj.)"],
          lustration=lus_muni(["Městské pozemky, sportovní investice, územní plán u Lužánek"]),
          sources=["iDNES", "Novinky 4/2026"]),
        L(id="brno-auto", bodyId=b, party="Motoristé sobě", short="AUTO",
          leader="Tomáš Kratochvíl", leaderRole="starosta Brno-Bystrc, dříve SOCDEM, 2025 nestraník za AUTO",
          results2022={"note": "Nová značka. Kratochvíl má starostenskou stopu v Bystrci."},
          topics=["Auta", "Bystrc a okraje", "Odpor k restrikcím"],
          promises=["Méně šikany řidičů", "Hlas městských částí na okraji"],
          summary="Motoristé s reálným starostou, ne jen celostátním billboardem. To je v Brně silnější než Sovová v Praze. Program pořád úzký.",
          trackRecord={"positive": ["Kratochvíl — Bystrc."], "negative": ["Přestup SOCDEM → AUTO, otázka věrnosti programu."]},
          controversies=["Odchod ze SOCDEM a kandidatura 2025 za AUTO"],
          sources=["Seznam Zprávy 3/2026", "Wikipedie ZMB 2026"]),
        L(id="brno-restart", bodyId=b, party="Restart pro Brno (KSČM, Stačilo!, ČSSD, DOMOV, Směr)", short="Restart",
          leader="Martin Říha", leaderRole="krajský zastupitel, KSČM",
          results2022={"predecessor": "KSČM a další levicové listiny zvlášť", "detail": "Letos jeden blok."},
          topics=["Levicový protest", "Sociální témata", "Stačilo!"],
          promises=["Restart města doleva", "Kritika pravicové koalice"],
          summary="Spočet kdysi zvlášť slabých listin. Říha je krajský, ne městská jednička s úřadem. Pro lustraci: hodně celostátního Stačilo v komunálu.",
          trackRecord={"positive": ["Krajská stopa KSČM/Stačilo."], "negative": ["Na magistrátu slabší než v kraji."]},
          controversies=["Značka Stačilo! a celostátní polarizace"],
          sources=["Metro 6/2026"]),
        L(id="brno-spd", bodyId=b, party="SPD a nezávislí", short="SPD",
          leader="Jiří Kment", leaderRole="zastupitel města Brna",
          results2022={"detail": "SPD mělo zastupitele; Kment a Prokeš v klubu."},
          topics=["Bezpečnost", "Migrace", "Kritika koalice"],
          promises=["Tvrdší postoj k pořádku", "Národní agenda v Brně"],
          summary="Kontinuita SPD v zastupitelstvu. Opozice s malou šancí na primátora, reálná šance hlídat radu zprava/protestně.",
          trackRecord={"positive": ["Mandáty a stálý klub."], "negative": ["Mimo radu, celostátní agenda."]},
          controversies=["Vnitrostranické tření (iDNES: soukmenovci SPD vlastní cestou)"],
          sources=["Metro 6/2026", "iDNES 4/2026"]),
        L(id="brno-naplno", bodyId=b, party="BRNO NAPLNO (Svobodní, Trikolora, PRO, Moravané)", short="Brno naplno",
          leader="Klára Liptáková", leaderRole="exnáměstkyně za KDU-ČSL, nyní PRO",
          results2022={"note": "Složení nové; Liptáková má stopu z lidovecké rady v minulosti."},
          topics=["Pravice mimo ODS", "Moravismus (partneři)", "PRO"],
          promises=["Jiné pravicové Brno než Vaňková/Zlatušková", "Méně „pražské“ politiky"],
          summary="Liptáková umí úřad, značka je ale sběr menších pravicových stran. Moravané dodávají identitu, ne většinu.",
          trackRecord={"positive": ["Zkušenost náměstkyně."], "negative": ["Přestup KDU → PRO, důvěra kmenových lidovců."]},
          controversies=["Ideový posun lídryně"],
          sources=["Wikipedie ZMB 2026"]),
        L(id="brno-nove", bodyId=b, party="Nové Brno", short="Nové Brno",
          leader="Michal Sedláček", leaderRole="architekt, bývalý městský architekt, Jižní čtvrť / nádraží",
          results2022={"note": "Nové hnutí, cca 15 členů v době vzniku."},
          topics=["Urbanismus", "Nádraží a jih", "Odbornost"],
          promises=["Město podle plánu, ne podle kšeftu", "Jižní čtvrť"],
          summary="Expertní listina k největší brněnské stavební kauze. Kompetence města u nádraží je sdílená se státem a SŽ — proto lustrace „prosazovat výš“.",
          trackRecord={"positive": ["Sedláček deset let u jižní čtvrti."], "negative": ["Malé hnutí, bez klubu 2022."]},
          controversies=["Spor o polohu nádraží — polarizace města"],
          lustration=lus_muni(["Územní plán, městské investice u jihu"], extra_up=["Správa železnic, ministerstvo dopravy, stát u nádraží"]),
          sources=["Wikipedie ZMB 2026"]),
        L(id="brno-prisaha", bodyId=b, party="Přísaha občanské hnutí", short="Přísaha",
          leader="Petr Vokřál", leaderRole="bývalý primátor Brna",
          results2022={"note": "Vokřál kdysi vyhrál město za ANO, později vlastní projekty. 2026 za Přísahu."},
          topics=["Návrat exprimátora", "Podnikatelský pragmatismus"],
          promises=["Zkušenost z čela města", "Protikorupční značka Přísahy"],
          summary="Známé jméno, slabší stroj. iDNES psal, že hrozí, že znovu pohoří. Stopa primátora je plus i mínus (očekávání).",
          trackRecord={"positive": ["Éra primátora, znalost úřadu."], "negative": ["Dlouho mimo aktuální koalici; riziko slabého výsledku."]},
          controversies=["Rozchody s ANO v minulosti"],
          sources=["iDNES 8/2026"]),
        L(id="brno-socdem", bodyId=b, party="Sociální demokracie (SOCDEM a NK)", short="SOCDEM",
          leader="Zdeněk Slavík", leaderRole="zastupitel Kohoutovice, Brněnské komunikace",
          results2022={"mandates": 3, "predecessor": "ČSSD Vaši starostové",
                       "detail": "3 mandáty. Všichni tři zastupitelé stranu opustili (Oliva, Štefan, Viskot). Štefan vypověděl koaliční smlouvu."},
          topics=["Sociální demokracie bez odpadlíků", "Městské firmy"],
          promises=["Návrat značky do zastupitelstva", "Sociální agenda"],
          summary="Značka přišla o klub, přesto kandiduje. Slavík je z městské firmy — to je znalost i střet. Voliči socdem mohou jít k Restartu, Žít/Zeleným nebo pryč.",
          trackRecord={"positive": ["Historie ČSSD v Brně."],
                       "negative": ["Ztráta všech 3 mandátů personálně.", "Rozpad klubu 2025/26."]},
          controversies=["Koaliční turistika Břetislava Štefana", "Kandidát z Brněnských komunikací"],
          sources=["Wikipedie ZMB 2026", "Novinky 8/2026"]),
        L(id="brno-b3", bodyId=b, party="Brno Brňankám a Brňanům! (VRBa a LANO)", short="B3!",
          leader="Matúš Bóna", leaderRole="právník",
          results2022={"note": "Nové / okrajové."},
          topics=["Občanský spolek B3!", "Právo"],
          promises=["Hlas „Brňanů“ mimo velké strany"],
          summary="Malá listina ze spolku. Spíš doplněk nabídky než uchazeč o primátora.",
          trackRecord={"positive": [], "negative": ["Bez mandátu."]},
          controversies=[],
          sources=["Wikipedie ZMB 2026"]),
        L(id="brno-dsz", bodyId=b, party="DSZ – Za práva zvířat a NK", short="DSZ",
          leader="Ivona Galová",
          results2022={"note": "Okrajová listina."},
          topics=["Práva zvířat"],
          promises=["Útulky a vyhlášky"],
          summary="Stejné téma jako v Praze. Město útulky ovlivní, zbytek programu je úzký.",
          trackRecord={"positive": ["Jasné téma."], "negative": ["Úzký záběr."]},
          controversies=[],
          lustration=lus_muni(["Městské útulky a vyhlášky"]),
          sources=["Brněnský deník 2026"]),
    ]


def pardubice():
    b = "pardubice"
    return [
        L(id="pce-ano", bodyId=b, party="ANO 2011", short="ANO",
          leader="Jan Nadrchal", leaderRole="úřadující primátor",
          results2022={"detail": "ANO vyhrálo, primátorem se po Charvátovi stal Nadrchal. Koalice ANO + Žijeme Pardubice + Společně pro Pardubice, těsná většina 20 z 39."},
          topics=["Kontinuita primátora", "Investice", "Vedení města"],
          promises=["Dotáhnout projekty", "Stabilita"],
          summary="Obhajoba radnice. Nadrchal už není nováček. Těsná koalice 20 hlasů znamená, že volby můžou město přehodit jedním klubem.",
          trackRecord={"positive": ["Primátorská zkušenost 2022–26 (nástup po Charvátovi).", "Většina v radě."],
                       "negative": ["Těsná koalice — křehkost.", "Únava z vládnutí."]},
          controversies=["Běžné spory opozice o transparentnost a investice (doplňovat z kampaně)"],
          sources=["Metro 7/2026", "Pardubický deník"]),
        L(id="pce-zijeme", bodyId=b, party="Žijeme Pardubice (s Pardubáky, Sdružením pro Pardubice, Patrioty, MY)", short="Žijeme",
          leader="Jakub Rychtecký", leaderRole="náměstek primátora",
          results2022={"predecessor": "Žijeme Pardubice (tehdy s ČSSD, ProPce21)",
                       "detail": "Koaliční partner ANO. Letos širší místní střecha, bez důrazu na ČSSD."},
          topics=["Místní značka", "Koaliční kontinuita", "Rozšíření partnerů"],
          promises=["Silnější místní blok", "Pokračovat ve vedení"],
          summary="Nejsilnější „pardubická“ značka vedle ANO. Rychtecký už úřad zná. Otázka, kam zmizeli voliči ČSSD z minulé střechy.",
          trackRecord={"positive": ["Účast v radě, náměstek."], "negative": ["Změna složení koalice na listině — jiná značka než 2022."]},
          controversies=[],
          sources=["Pardubický deník", "Metro 7/2026"]),
        L(id="pce-prog", bodyId=b, party="Progresivní Pardubice (Piráti a TOP 09, podpora Zelených)", short="Progresivní",
          leader="Martin Slezák", leaderRole="zastupitel, právník a dopravní inženýr, TOP 09",
          results2022={"note": "Nová střecha. Piráti, TOP 09 a Zelení dřív zvlášť / v jiných blocích. Teď opoziční spojenectví."},
          topics=["Zrušení městských obvodů", "Klima", "Trolejbusy"],
          promises=["Zrušit MO", "Adaptace na klima", "Víc trolejbusů"],
          summary="Nejčitelnější programový experiment: zrušit 8 obvodů. To zastupitelstvo města teoreticky může tlačit (organizace města), ale je to velký konflikt se starosty obvodů.",
          trackRecord={"positive": ["Slezák a Hrdina už jsou zastupitelé.", "Jasná dopravní expertíza."],
                       "negative": ["Opozice bez gescí 2022–26 v tomto složení."]},
          controversies=["Návrh zrušit obvody — ostře proti struktuře města"],
          lustration=lus_muni(
              ["Sloučení/zrušení městských obvodů je městská organizace", "MHD / trolejbusy v gesci města"],
              extra_up=["Kraj a stát u velkých dopravních staveb"],
          ),
          sources=["Pardubický deník", "Novinky kandidáti 555134"]),
        L(id="pce-ods", bodyId=b, party="ODS Pardubice", short="ODS",
          leader="Ondřej Tichý", leaderRole="podnikatel, předseda spolku",
          results2022={"predecessor": "Část značky šla ve Společně pro Pardubice",
                       "detail": "Letos samostatná ODS. Společně pro Pardubice bylo v koalici s ANO."},
          topics=["Pravice", "Podnikání", "Město bez velké koalice s ANO (v kampani)"],
          promises=["Občanskodemokratická správa", "Investice s rozvahou"],
          summary="ODS se letos nevejde do starého „Společně“. Tichý je mladší tvář. Část pravicových voličů může zůstat u vzpomínky na koaliční Společně.",
          trackRecord={"positive": ["Zastupitelská stopa ODS ve městě."], "negative": ["Rozpad dřívější střechy, nejasný převod mandátů 2022."]},
          controversies=[],
          sources=["Pardubický deník", "Novinky"]),
        L(id="pce-lidovci", bodyId=b, party="Noví lidovci a Nestraníci", short="KDU+",
          leader="Petr Netolický",
          results2022={"detail": "Lidovci hledali koaliční partnery, nenašli — jdou s nestraníky. Na listině mj. Vít Ulrych."},
          topics=["Školství a sport", "Konzervativní střed", "Nestraníci"],
          promises=["Služby, kluby, uměřenost"],
          summary="KDU bez velkého partnera. Netolický je známé krajské/městské jméno. Riziko: sami pod prahem, pokud se hlasy neposkládají.",
          trackRecord={"positive": ["Dlouhá personální stopa ve městě a kraji."], "negative": ["Izolace na kandidátce 2026."]},
          controversies=[],
          sources=["Metro 7/2026", "Novinky"]),
        L(id="pce-stan", bodyId=b, party="STAROSTOVÉ A NEZÁVISLÍ", short="STAN",
          leader="Daniel Vondra", leaderRole="politolog, aktivista (manželství pro všechny); 2. Jiří Hájek, exposlanec",
          results2022={"detail": "STAN ve městě měli zastoupení; letos nový lídr mimo klasického starostu."},
          topics=["Občanská práva", "Projektový management", "Opozice"],
          promises=["Otevřenější město", "Jiné akcenty než ANO"],
          summary="STAN s aktivistickým lídrem. Hájek na dvojce dodává parlamentní jméno. Otázka, jestli pardubický STAN chce spíš slušnost, nebo kulturní válku.",
          trackRecord={"positive": ["Celostátní značka STAN."], "negative": ["Lídr bez primátorské stopy."]},
          controversies=["Téma manželství pro všechny je spíš zákon, ne vyhláška města"],
          lustration=lus_muni(extra_no=["Manželství / občanský zákoník — Sněmovna a Senát"]),
          sources=["Metro 7/2026"]),
        L(id="pce-spd", bodyId=b, party="SPD s podporou Trikolory, Svobodných a NK", short="SPD+",
          leader="Leoš Janda", leaderRole="zastupitel, Trikolora, technický ředitel",
          results2022={"detail": "SPD měli zastupitele. Jednička je z Trikolory na listině SPD."},
          topics=["Protest", "Trikolora uvnitř SPD listiny"],
          promises=["Tvrdší opozice", "Národní agenda"],
          summary="Stejný vzorec jako jinde: SPD půjčuje lístek menším značkám. Janda už v zastupitelstvu je.",
          trackRecord={"positive": ["Mandát, znalost jednání."], "negative": ["Mimo radu."]},
          controversies=[],
          sources=["Novinky kandidáti Pardubice", "Pardubický deník"]),
        L(id="pce-nase", bodyId=b, party="NAŠE PARDUBICE – „Nechme město rozkvést“", short="Naše Pardubice",
          leader="Filip Sedlák", leaderRole="zastupitel, pedagog, protikorupční aktivista",
          results2022={"detail": "Sedlák vedl listinu i před čtyřmi lety, mandát mají."},
          topics=["Protikorupce", "Kontrola radnice", "Městská zeleň (slogan)"],
          promises=["Hlídání zakázek", "Otevřenost"],
          summary="Lokální kontrolní značka. Nejsou velká koalice, jsou nepříjemní v interpelacích — to je jejich produkt.",
          trackRecord={"positive": ["Kontinuita lídra a mandátu."], "negative": ["Bez gescí, omezený výkon."]},
          controversies=["Konflikty s radnicí v mediálním prostoru (typické pro aktivistický klub)"],
          sources=["Pardubický deník", "Novinky"]),
        L(id="pce-srdcem", bodyId=b, party="Srdcem pro Pardubice", short="Srdcem",
          leader="Josef Rak",
          results2022={"note": "Menší / novější listina vůči velké šestce."},
          topics=["Lokální sdružení"],
          promises=["Město srdcem — měkká lokální agenda"],
          summary="Devátá listina. Pro voliče mimo strany. Bez silné stopy v radě 2022 v tomto názvu.",
          trackRecord={"positive": [], "negative": ["Slabší viditelnost."]},
          controversies=[],
          sources=["Pardubický deník"]),
    ]


def senate():
    out = []
    def S(id, body, party, leader, res, summary, topics, **kw):
        kw.setdefault("lustration", lus_sen())
        return L(id=id, bodyId=body, party=party, leader=leader, results2022=res,
                 summary=summary, topics=topics, **kw)

    out += [
        S("s21-laska", "sen-21", "SEN 21", "Václav Láska",
          {"note": "Obhajoba. Senát 2020 (ne 2022 — obvody se střídají).", "detail": "Úřadující senátor obvodu 21."},
          "Obhájce. Současně vede magistrátní SEN pro Prahu. Senát ovlivní zákony, ne parkování na Smíchově — to říká lustrace.",
          ["Obhajoba", "Liberální střed", "Justice / dohled"]),
        S("s21-broz", "sen-21", "ANO", "Lubomír Brož",
          {"note": "ANO v obvodu 2020 neuspělo na mandát (obvod drží Láska)."},
          "Radní MČ Praha 5, ekonom. Tvář ANO pro Smíchov a okolí. Městskou část zná, Senát je jiná hra.",
          ["MČ Praha 5", "ANO"]),
        S("s21-sablik", "sen-21", "Koalice ODS, KDU-ČSL a STAN", "Radko Sáblík",
          {"note": "Školská tvář (Smíchovská SPŠ)."},
          "Ředitel známé školy. Koalice tří vládních značek proti Láskovi. Téma školství je spíš ministerstvo, on může tlačit zákony.",
          ["Školství", "SPOLU/STAN blok"],
          lustration=lus_sen(extra_can=["Školské zákony ve spolupráci se Sněmovnou"])),
        S("s21-sarapatka", "sen-21", "Koalice TOP 09, Piráti a LES", "Zdeněk Šarapatka",
          {"note": "Publicista, bývalý radní ČT."},
          "Mediální jméno na středopravé listině mimo ODS blok. Štěpí antivládní i vládní voliče.",
          ["Média", "Komentátorská značka"]),
        S("s21-spirov", "sen-21", "SPD (podpora PRO)", "Pavel Spirov",
          {"note": "SPD v obvodu."},
          "Vysokoškolský pedagog za SPD. Protestní hlas v Praze 5.",
          ["SPD", "PRO"]),
        S("s21-proksanova", "sen-21", "KSČM (podpora ČSSD a KSČ)", "Petra Prokšanová",
          {"note": "Levicová listina."},
          "Socioložka na spojené levici. V Praze 5 těžký obvod pro KSČM.",
          ["Levice"]),
        S("s21-augustin", "sen-21", "Přísaha", "Ľubomír Augustín",
          {"note": "Přísaha."},
          "Právník a ekonom. Malá značka v senátním poli.",
          ["Přísaha"]),
        S("s24-smoljak", "sen-24", "STAN + Piráti + KDU-ČSL + Zelení + TOP 09 (podpora LES)", "David Smoljak",
          {"note": "Obhajoba, senátor od 2020. Cimrmanolog, média."},
          "Široká středová střecha na obhájce. Smoljak je známý bojovník o nezávislost médií — to je senátní téma (rady, zákony), ne svoz odpadu v Letňanech.",
          ["Obhajoba", "Média", "Široká koalice"],
          lustration=lus_sen(extra_can=["Mediální legislativa, rady ČT/ČRo v mezích zákona"])),
        S("s24-peckova", "sen-24", "ODS", "Dagmar Pecková",
          {"note": "Nová kandidátka, operní pěvkyně."},
          "Celebrity kandidátka ODS. Mediálně nejsilnější jméno obvodu vedle Smoljaka. Zkušenost ze Senátu nulová, známost vysoká.",
          ["Kultura", "ODS"],
          controversies=["Otázka, zda je kampaň o obvodu, nebo o jménu"]),
        S("s24-zalud", "sen-24", "ANO", "Radek Žalud",
          {"note": "ANO, IT, hudebník. (V přehledech dříve i Roman Žalud — oficiálně Radek.)"},
          "ANO proti obhájci a Peckové. Méně známý než oba favorité.",
          ["ANO"]),
        S("s24-laube", "sen-24", "Svobodní + SPD + Trikolora + PRO", "Bedřich Laube",
          {"note": "Zároveň lídr Svobodných na magistrátu."},
          "Pravicově-protestní blok. Dvojí kampaň: ZHMP i Senát.",
          ["Svobodní", "SPD blok"]),
        S("s24-batyiova", "sen-24", "Hnutí Kruh", "Darina Batyiová",
          {"note": "Kruh."},
          "Finanční analytička. Malá značka, senátní kampaň jako zviditelnění.",
          ["Kruh"]),
        S("s27-padevet", "sen-27", "STAN + ODS + Piráti + TOP 09", "Jiří Padevět",
          {"note": "Obvod drží Miroslava Němcová (ODS), letos nekandiduje v přehledech jako obhájkyně na této listině — střecha je širší, jednička Padevět."},
          "Spisovatel a nakladatel na široké koalici. Praha 1 je prestižní obvod, 9 kandidátů — nejvíc v ČR.",
          ["Kultura", "Široká koalice"]),
        S("s27-cizinskyj", "sen-27", "Praha sobě + Zelení + KDU-ČSL + SEN 21", "Jan Čižinský",
          {"note": "Exstarosta Prahy 7, tvář Prahy sobě. Na magistrátu je na 3. místě."},
          "Nejsilnější lokální značka širšího centra. Senát vs. magistrát — Čižinský umí obojí vyprávět jako službu Praze.",
          ["Praha sobě", "Centrum"]),
        S("s27-cizinskyp", "sen-27", "Levice", "Pavel Čižinský",
          {"note": "Přešel z obvodu 24 na 27. Zároveň magistrátní jednička Levice."},
          "Dva Čižinští v jednom obvodu — volič musí číst jméno. Pavel je Levice, Jan je Praha sobě.",
          ["Levice", "Bydlení"]),
        S("s27-dudra", "sen-27", "ANO", "Ján Dudra",
          {"note": "Náhrada za Karla Grabeina Procházku."},
          "Lékař, ANO. Personální změna na poslední chvíli.",
          ["ANO", "Zdravotnictví"],
          controversies=["Výměna kandidáta ANO"]),
        S("s27-stern", "sen-27", "TEAM", "Jan Štern",
          {"note": "Producent, souvislost s JSME PRAHA / TEAM."},
          "Kulturní jméno na nové značce. Spíš doplněk magistrátní kampaně Komrskové.",
          ["TEAM"]),
        S("s27-ryvola", "sen-27", "GEN", "Vojtěch Ryvola",
          {"note": "Radní MČ Praha 1."},
          "Lokální radní na celostátní listině GEN. Zná Prahu 1, Senát je skok.",
          ["Praha 1", "GEN"]),
        S("s27-morstadt", "sen-27", "Generace", "Jiří Morštadt",
          {"note": "Podnikatel, vydavatel."},
          "Další malá značka v přeplněném obvodu.",
          ["Generace"]),
        S("s27-kolman", "sen-27", "SOCDEM", "Vladimír Kolman",
          {"note": "Sociální demokracie."},
          "SOCDEM v centru Prahy. Těžký obvod.",
          ["SOCDEM"]),
        S("s27-pesek", "sen-27", "Švýcarská demokracie", "Pavel Pešek",
          {"note": "Okrajová značka."},
          "Přímá demokracie v názvu. Senát referenda celostátně nenařídí sám.",
          ["Přímá demokracie"]),
        S("s60-papousek", "sen-60", "ODS + KDU-ČSL + Piráti + Fakt Brno + TOP 09", "Zdeněk Papoušek",
          {"note": "Obhajoba, senátor Brno-město.", "detail": "Široká střecha včetně Pirátů a Fakt Brno."},
          "Úřadující senátor se širokou podporou napříč koalicí i částí opozice magistrátu. Těžko ho vyřadit v 1. kole, ale Brno je polarizované.",
          ["Obhajoba", "Široká koalice"]),
        S("s60-zitterbart", "sen-60", "STAN", "Karel Zitterbart",
          {"note": "Obhajuje mandát, ale z obvodu 57 Vyškov — teď kandiduje v Brně. Obvod 57 letos taky volí, on tam nejde."},
          "Přestup senátora do Brna. STAN vs. široký blok Papouška. Lékař, známý z Vyškova.",
          ["STAN", "Přestup obvodu"],
          controversies=["Opouští obvod 57, kde se taky volí"]),
        S("s60-sterba", "sen-60", "ANO", "Jaroslav Štěrba",
          {"note": "Prof. MUDr., FN Brno prostředí."},
          "Silné lékařské jméno ANO v univerzitním městě. Kompetence Senátu u fakultní nemocnice je zákonodárná, ne ředitelská.",
          ["ANO", "Zdravotnictví"],
          lustration=lus_sen(extra_can=["Zdravotní zákony"], extra_no=["Jmenování ředitele FN — ministerstvo/zřizovatel"])),
        S("s60-turanek", "sen-60", "SPD (podpora PRO, JaSaN)", "Jaroslav Turánek",
          {"note": "SPD."},
          "Profesor, SPD. Odborná vizitka na protestní značce.",
          ["SPD"]),
        S("s60-samkova", "sen-60", "Stačilo!", "Klára Alžběta Samková",
          {"note": "Advokátka, Praha 2 — kandiduje v Brně."},
          "Celostátní tvář Stačilo! v Brně. Medializace osobnosti často přebije obvod.",
          ["Stačilo!"],
          controversies=["Trvalé bydliště mimo Brno", "Mediální spory Samkové"]),
        S("s60-holcnerova", "sen-60", "Hnutí Kruh", "Veronika Holcnerová",
          {"note": "Kruh, inženýrka, Brno."},
          "Lokální Kruh proti velkým blokům. Malá šance, čitelná alternativa.",
          ["Kruh"]),
    ]
    return out


def main():
    payload = {
        "meta": {
            "elections": "Komunální a senátní volby 9.–10. 10. 2026",
            "secondRoundSenate": "16.–17. 10. 2026",
            "cities": ["Praha", "Brno", "Pardubice"],
            "note": "Senát jen obvody 21, 24, 27, 60. Pardubice (obvod 43) se letos nevolí. MČ kandidátky: ČSÚ blokoval stažení.",
            "updated": "2026-09-09",
        },
        "bodies": bodies(),
        "lists": praha() + brno() + pardubice() + senate(),
    }
    js = "window.VOLBY = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    Path("data.js").write_text(js, encoding="utf-8")
    Path("data/volby.json").parent.mkdir(parents=True, exist_ok=True)
    Path("data/volby.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"bodies={len(payload['bodies'])} lists={len(payload['lists'])}")


if __name__ == "__main__":
    main()
